### ISSUE TITLE
Project Approved

### ISSUE THREAD

**Issue by dbc2201** [Nishita-Maheshwari/Personality-Detection-from-tweets#1]
I see potential in the software proposed.  
I would like to go forth in claiming acceptance of this project and henceforth offer my services as the project mentor for the same.  
Here are some points you must take care of -  
1. ALL of your project code must be regularly committed to GIT and pushed via pull requests to GITHUB. I will create the GitHub repository for you and maintain the technical configuration aspects and would go through the code reviews, and pull requests.  
2. Every project team is required to hold a mandatory meeting with their mentors at least once a week, the same goes for you as well.  
3. Your GitHub contributions chart would determine the final grade of your project.  
4. Moving forward, you need to submit the synopsis for this project (look at the format
provided here – https://gist.github.com/dbc2201/efcc0c23e942056b185e1171cc3c440a).  
5. The above-stated document is to be written in LaTeX ONLY! Here is a short intro video -
https://youtu.be/VhmkLrOjLsw  
6. Please proofread your synopsis before emailing it back to me.  
7. Select your technology stack properly and send me the list of requirements about the
same so I can configure the GitHub repo to tailor the needs of the project.  
8. The project would most likely work with TDD (Test-Driven Development), which I presume you might have learnt
about in your software engineering class. So kindly get brushed up on that.

**Comment by dbc2201** [comment]
Kindly submit a synopsis on or before 15th February 2020 06:00 p.m via email.

**Comment by Nishita-Maheshwari** [comment]
Ok sir ,we will correct our synopsis accordingly and will submit till 15 feb
