### ISSUE TITLE
Synopsis Approved

### ISSUE THREAD

**Issue by dbc2201** [Nishita-Maheshwari/Personality-Detection-from-tweets#2]
Kindly move ahead with your project and firstly, mention here the technology stack that you are going to use so that I can create a repository tailored to those.

**Comment by Nishita-Maheshwari** [comment]
we mention technology in synopsis "machine learning with python"

**Comment by dbc2201** [comment]
Yes, I've read that, you'll have to be a bit more specific I'm afraid.

**Comment by Nishita-Maheshwari** [comment]
We added some technologies. Kindly checked it if it is not satisfied or correct then we will meet you on monday .
